### ISSUE TITLE
vector confussion

### ISSUE THREAD

**Issue by yly12334** [gillislab/Coexpression_Proxies#3]
### **hello, ,I am reviewing a function in the paper and have a question regarding some of its variables. Specifically, I'd like to understand the variables common_name_1 and common_name_2 in the function below: **

```
def Calculate_Score_list_for_thresholding(orthology_map,species_1_coexpression_network,species_2_coexpression_network):
    import pandas as pd
    #Get Species Names in Common form 


    cross_species_n_m_genes = pd.read_csv(orthology_map)
    orig_column_common_name_1 = common_name_1 + ' Symbol'
    orig_column_common_name_2 = common_name_2 + ' Symbol'
```
Could you please explain what these variables represent and how they should be defined?

Thank you for your help.

**Comment by mikepassal** [comment]
Hi Yang. Yes, these refer to column names in the orthology file.  I've attached an example file to clarify
[maize_to_arabidopsis_ortholog_NM.csv](https://github.com/user-attachments/files/18014208/maize_to_arabidopsis_ortholog_NM.csv)

**Comment by yly12334** [comment]
> Hi Yang. Yes, these refer to column names in the orthology file. I've attached an example file to clarify [maize_to_arabidopsis_ortholog_NM.csv](https://github.com/user-attachments/files/18014208/maize_to_arabidopsis_ortholog_NM.csv)

Thanks so much for the example. This is very useful and helpful~
